# Generated by Django 6.0.6 on 2026-07-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_stock_variant_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='ebooks/pdf/')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shop.ebook')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
